### ISSUE TITLE
Upgrade to jasmine-ajax 3.0.0

### ISSUE THREAD

**Issue by mzabriskie** [IDCubed/karma-jasmine-ajax#11]
Apparently `request.respondWith` didn't make it into 2.99.0. Need to upgrade to 3.0.0.

**Comment by jacobbuck** [comment]
The official [karma-jasmine](https://github.com/karma-runner/karma-jasmine) has [unbundled](https://github.com/karma-runner/karma-jasmine#jasmine-20-docs) the jasmine library from it, might be worth doing a similar approach here? :thought_balloon:

**Comment by mzabriskie** [comment]
@jacobbuck so with this approach you would have to do something like:

`$ npm install --save-dev karma-jasmine-ajax jasmine-ajax`

Is that accurate? If so I fully support this. It would allow updating to latest jasmine-ajax without requiring a PR and release of karma-jasmine-ajax.

**Comment by jacobbuck** [comment]
@mzabriskie yep, that's right :ok_hand:
