### ISSUE TITLE
npm info shows wrong peerDependencies

### ISSUE THREAD

**Issue by ogonkov** [IDCubed/karma-jasmine-ajax#20]
`npm info` shows wrong peerDependencies for `karma-jasmine-ajax` package.

At Github `peerDependencies` in `package.json` is `"karma": ">=0.12.0"`, but when i try to install it via `npm`, it's failed, because here is `~0.12.0` for some reason.

```bash
$ npm info karma-jasmine-ajax | grep peerDependencies
  peerDependencies: { karma: '~0.12.0' },
```

How to fix it?

**Comment by grahamkennery** [comment]
I think it's just gotta be published to npm
@pdeegan Any chance you could publish it?

**Comment by ogonkov** [comment]
Looks like it's fixed now& Tanks guys!
```bash
$ npm info karma-jasmine-ajax | grep peerDependencies
  peerDependencies: { karma: '>=0.12.0' },
```
